
name: CI
on:
  push:
    branches:
      - main
  schedule:
    - cron: '* * * * *'
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        Plan: [1,2,3,4]
    steps:
      - name: Clone repository
        uses: actions/checkout@v3

      - name: Auto green
        run: |
          git config --local user.email "1v512egv@duck.com"
          git config --local user.name "1v512egv"
          git remote set-url origin https://${{ github.actor }}:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}
          git pull --rebase
          git commit --allow-empty -m "gogreen"
          git push
